In [ ]:
import pandas as pd
import numpy as np
from numpy import array
from sklearn.preprocessing import OneHotEncoder

data = ['cold', 'cold', 'warm', 'cold', 'hot', 'hot', 'warm', 'cold', 'warm', 'hot']
values = array(data)
print(values)

# binary encode
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)

['cold' 'cold' 'warm' 'cold' 'hot' 'hot' 'warm' 'cold' 'warm' 'hot']
[[1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]


In [ ]:
import pandas as pd
import numpy as np

data = pd.read_excel( '/content/Book5.xlsx')
print(data)

from sklearn.preprocessing import OneHotEncoder 
from sklearn.compose import ColumnTransformer 

columnTransformer = ColumnTransformer([('encoder',OneHotEncoder(),[1])],remainder='passthrough') 
  
data = np.array(columnTransformer.fit_transform(data))

columnTransformer = ColumnTransformer([('encoder',OneHotEncoder(),[2])],remainder='passthrough') 
  
data = np.array(columnTransformer.fit_transform(data))
data

   Day   Outlook    Wind PlayTennis
0    1     Sunny    Weak         No
1    2     Sunny  Strong         No
2    3  Overcast    Weak        Yes
3    4      Rain    Weak        Yes
4    5      Rain    Weak        Yes
5    6      Rain  Strong         No
6    7  Overcast  Strong        Yes


array([[0.0, 1.0, 1, 'Sunny', 'No'],
       [1.0, 0.0, 2, 'Sunny', 'No'],
       [0.0, 1.0, 3, 'Overcast', 'Yes'],
       [0.0, 1.0, 4, 'Rain', 'Yes'],
       [0.0, 1.0, 5, 'Rain', 'Yes'],
       [1.0, 0.0, 6, 'Rain', 'No'],
       [1.0, 0.0, 7, 'Overcast', 'Yes']], dtype=object)

In [5]:
import pandas as pd
import numpy as np

data = pd.read_csv( '/content/Book6.csv')
print(data)

from sklearn.preprocessing import OneHotEncoder 
from sklearn.compose import ColumnTransformer 

columnTransformer = ColumnTransformer([('encoder',OneHotEncoder(),[2,5])],remainder='passthrough') 
  
data = np.array(columnTransformer.fit_transform(data))

data

  Day   Outlook Temperature Humidity    Wind Play Tennis
0  D1     Sunny         Hot     High    Weak          No
1  D2     Sunny         Hot     High  Strong          No
2  D3  Overcast         Hot     High    Weak         Yes
3  D4      Rain        Mild     High    Weak         Yes
4  D5      Rain        Cool   Normal    Weak         Yes
5  D6      Rain        Cool   Normal  Strong          No


array([[0.0, 1.0, 0.0, 1.0, 0.0, 'D1', 'Sunny', 'High', 'Weak'],
       [0.0, 1.0, 0.0, 1.0, 0.0, 'D2', 'Sunny', 'High', 'Strong'],
       [0.0, 1.0, 0.0, 0.0, 1.0, 'D3', 'Overcast', 'High', 'Weak'],
       [0.0, 0.0, 1.0, 0.0, 1.0, 'D4', 'Rain', 'High', 'Weak'],
       [1.0, 0.0, 0.0, 0.0, 1.0, 'D5', 'Rain', 'Normal', 'Weak'],
       [1.0, 0.0, 0.0, 1.0, 0.0, 'D6', 'Rain', 'Normal', 'Strong']],
      dtype=object)