<a href="https://colab.research.google.com/github/manavshah123/Data-Science-and-machine-learning/blob/main/DS_MLprac2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Anaconda framework
import numpy as np
import matplotlib. pyplot as pit
import pandas as pd

#Classes and inbuilt methods
#Importing the dataset
dataset = pd. read_csv( '/content/drive/MyDrive/Colab Notebooks/Dataset/dataset1.csv' ) # XLSX read_ex
dataset . shape
# divide my dataset into 2 parts - input and output

dataset . info( )
x = dataset . iloc[ :, :-1]. values
y = dataset . iloc[ :, -1]. values


from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean' )
imputer = imputer.fit(x[: , 1:3])
x[ :, 1:3] = imputer . transform(x[ : , 1:3])
print(x)

from sklearn. preprocessing import LabelEncoder
labelencoder_x = LabelEncoder()
x[:, 0] = labelencoder_x. fit_transform(x[: , 0])
print (x)

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)


from sklearn. preprocessing import StandardScaler
sc_x = StandardScaler()
x_train = sc_x. fit_transform(x_train)
x_test = sc_x. transform(x_test)


dataset = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Dataset/dataset2.csv')
x=dataset.iloc[:, :].values

#Encoding categorical data
from sklearn. preprocessing import LabelEncoder, OneHotEncoder
from sklearn. compose import ColumnTransformer
transform = ColumnTransformer([ ("Col 0", OneHotEncoder( ) , [0]) ],remainder = 'passthrough')
x= transform. fit_transform(x)
transform = ColumnTransformer( [ ("Column 4 converted", OneHotEncoder ( ) , [4]) ],remainder = 'passthrough' )
x= transform. fit_transform(x)

transform = ColumnTransformer([("Outlook_OLO_OL1", OneHotEncoder ( ) , [6]) ],remainder = 'passthrough')
x = transform. fit_transform(x)
print (x. astype(int) )

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    10 non-null     object 
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     object 
dtypes: float64(2), object(2)
memory usage: 448.0+ bytes
[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
[[0 44.0 72000.0]
 [2 27.0 48000.0]
 [1 30.0 54000.0]
 [2 38.0 61000.0]
 [1 40.0 63777.77777777778]
 [0 35.0 58000.0]
 [2 38.77777777777778 52000.0]
 [0 48.0 79000.0]
 [1 50.0 83000.0]
 [0 37.0 67000.0]]
[[1 0 0 0 0 0 0 1 0 0 1]
 [0 1 0 0 0 0 0 1 0 0 1]
 [0 0 1 0 0 1 0 0 1 0 0]
 [0 0 0 1 0 0 1 0 0 1 0]
 [0 0 0 0 1 0 1 0 0 1 0]