In [7]:
import numpy as np
np.zeros((2,3))
np.zeros(5)

np.zeros((2,3,3))

np.ones((2,3), dtype='int32')
np.full((2,2),99,dtype='int32')



array([[4, 4, 4],
       [4, 4, 4]])

In [9]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])

np.full_like(a,4)

array([[4, 4, 4],
       [4, 4, 4]])

In [10]:
import numpy as np
#identity matrix

np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [11]:
import numpy as np

#2nd way to createidentity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
import numpy as np

#reshape array
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a)
b=a.reshape((4,2))
print(b)
c=a.reshape((2,2,2))
print(c)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [21]:
import numpy as np

#vertical stack 2d array using vstack and for horiz Hstack

v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

np.hstack([v1,v2,v1,v2])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8])